export const DETAILS = {
  START: 'DETAILS_START',
  COMPLETE: 'DETAILS_COMPLETE',
  ERROR: 'DETAILS_ERROR',
  OPEN_LIST: 'DETAILS_OPEN_LIST',
  CLOSE_LIST: 'DETAILS_CLOSE_LIST',
}

export const SEARCH = {
  ADD: 'SEARCH_ADD',
  REMOVE: 'SEARCH_REMOVE',
}
