export const DETAILS = {
  START: 'DETAILS_START',
  COMPLETE: 'DETAILS_COMPLETE',
  ERROR: 'DETAILS_ERROR',
  OPEN_LIST: 'DETAILS_OPEN_LIST',
  CLOSE_LIST: 'DETAILS_CLOSE_LIST',
  UPDATE_START: 'DETAILS_UPDATE_START',
  UPDATE_COMPLETE: 'DETAILS_UPDATE_COMPLETE',
}

export const SEARCH = {
  ADD: 'SEARCH_ADD',
  REMOVE: 'SEARCH_REMOVE',
}

export const MARKET = {
  REQUEST: 'MARKET_START',
  SUCCESS: 'MARKET_SUCCESS',
  FAILURE: 'MARKET_FAILURE'
}
